export const UPDATE_SAVED_JOBS = "UPDATE_SAVED_JOBS";
export const UPDATE_APP_JOBS = "UPDATE_APP_JOBS";
export const UPDATE_LOGIN = "UPDATE_LOGIN";

export const ADD_SAVED_JOB = "ADD_SAVED_JOB";
export const ADD_APP_JOB = "ADD_APP_JOB";

export const REMOVE_SAVED_JOB = "REMOVE_FROM_CART";